### ISSUE TITLE
Headful runs failing

### ISSUE THREAD

**Issue by hugomrdias** [microsoft/playwright-github-action#37]
in the last couple of days i noticed headful tests failing with this error 

https://github.com/hugomrdias/playwright-test/runs/1564450527?check_suite_focus=true#step:7:42 
im still trying to track down the reason doesn’t seem to be related to playwright itself probably something changed in the github actions ubuntu env.

**Comment by mxschmitt** [comment]
> in the last couple of days i noticed headful tests failing with this error
> 
> https://github.com/hugomrdias/playwright-test/runs/1564450527?check_suite_focus=true#step:7:42
> im still trying to track down the reason doesn’t seem to be related to playwright itself probably something changed in the github actions ubuntu env.

I don't see something which directly gives me a hint why its not working, but maybe you could try ubuntu20 instead of ubuntu18. Does it fail for every run or only occasionally?

**Comment by hugomrdias** [comment]
```
    [err] [8866:8866:1216/145638.007421:ERROR:browser_main_loop.cc(1435)] Unable to open X display.
    ============================================================
    Note: use DEBUG=pw:api environment variable and rerun to capture Playwright logs.
    at Connection.sendMessageToServer (/home/runner/work/playwright-test/playwright-test/node_modules/playwright-core/lib/client/connection.js:69:15)
    at Proxy.<anonymous> (/home/runner/work/playwright-test/playwright-test/node_modules/playwright-core/lib/client/channelOwner.js:44:61)
    at /home/runner/work/playwright-test/playwright-test/node_modules/playwright-core/lib/client/browserType.js:82:48
    at async BrowserType._wrapApiCall (/home/runner/work/playwright-test/playwright-test/node_modules/playwright-core/lib/client/channelOwner.js:72:28)
    at makeError (/home/runner/work/playwright-test/playwright-test/node_modules/execa/lib/error.js:59:11)
    at handlePromise (/home/runner/work/playwright-test/playwright-test/node_modules/execa/index.js:114:26)
    at async Object.handler (/home/runner/work/playwright-test/playwright-test/test.js:37:18)
    at async Number.runner (/home/runner/work/playwright-test/playwright-test/node_modules/uvu/dist/index.js:77:5)
    at async exec (file:///home/runner/work/playwright-test/playwright-test/node_modules/uvu/dist/index.mjs:131:33)
    at async Module.run (file:///home/runner/work/playwright-test/playwright-test/node_modules/uvu/run/index.mjs:13:2)
    at async /home/runner/work/playwright-test/playwright-test/node_modules/uvu/bin.js:26:5
```

it always fails that workflow specifically is using ubuntu-latest which is still 18.04.5 

`xvfb-run -a yarn test` in linux used to work for headful but now it doesn't

**Comment by n8henrie** [comment]
I'm also having headful runs fail, with a python playwright project. I've tried a ton of different configurations (ubuntu-18, ubuntu-20, macos-latest) with no luck at all. Getting `Unable to open X display` with `xvfb-run --auto-servernum python -m tox -e py`.

https://github.com/n8henrie/pycookiecheat/blob/dd41a031de4fc116a918004db878e3a99f0eb4b7/.github/workflows/python-package.yml

**Comment by n8henrie** [comment]
@hugomrdias -- did you close this because it is working again for you?

**Comment by hugomrdias** [comment]
Yes

Hugo Dias
